version: '3'
services:
  web:
    image: php:apache
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
      - "443:443"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: prueba2024
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
