version: '3'
services:
  web:
#    image: php:apache
    container_name: php_apache_container
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/   # Keep the vendor files in the host
    links:
      - db
    #  - redis
    ports:
      - "8080:80"
      - "443:443"
    environment:
      DB_HOST: db
      DB_DATABASE: prueba2024
      DB_USERNAME: user
      DB_PASSWORD: password
    #  REDIS_HOST: redis
    #  SESSION_DRIVER: redis
    #  CACHE_DRIVER: redis
    #  XDEBUG_CONFIG: remote_host=192.168.0.172
  db:
    # image: mysql:latest
    container_name: mysql_container
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    ports:
      - "3306:3306"
#   redis:
#    image: redis:4.0-alpine
#    ports:
#      - 16379:6379
